// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcEquiposDeFutbol.Data;

#nullable disable

namespace EquiposDeFutbol.Migrations
{
    [DbContext(typeof(MvcEquiposDeFutbolContext))]
    [Migration("20230607004229_resetJugador")]
    partial class resetJugador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("EquipoJugador", b =>
                {
                    b.Property<int>("EquiposId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JugadoresJugadorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EquiposId", "JugadoresJugadorId");

                    b.HasIndex("JugadoresJugadorId");

                    b.ToTable("EquipoJugador");
                });

            modelBuilder.Entity("EquiposDeFutbol.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnioFundacion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadSocios")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LigaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Titulos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LigaId");

                    b.ToTable("Equipo");
                });

            modelBuilder.Entity("EquiposDeFutbol.Models.Jugador", b =>
                {
                    b.Property<int>("JugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("JugadorId");

                    b.ToTable("Jugador");
                });

            modelBuilder.Entity("EquiposDeFutbol.Models.Liga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Liga");
                });

            modelBuilder.Entity("EquipoJugador", b =>
                {
                    b.HasOne("EquiposDeFutbol.Models.Equipo", null)
                        .WithMany()
                        .HasForeignKey("EquiposId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquiposDeFutbol.Models.Jugador", null)
                        .WithMany()
                        .HasForeignKey("JugadoresJugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EquiposDeFutbol.Models.Equipo", b =>
                {
                    b.HasOne("EquiposDeFutbol.Models.Liga", "Liga")
                        .WithMany("Equipos")
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liga");
                });

            modelBuilder.Entity("EquiposDeFutbol.Models.Liga", b =>
                {
                    b.Navigation("Equipos");
                });
#pragma warning restore 612, 618
        }
    }
}
