// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcEquiposDeFutbol.Data;

#nullable disable

namespace EquiposDeFutbol.Migrations
{
    [DbContext(typeof(MvcEquiposDeFutbolContext))]
    [Migration("20230426224737_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("EquiposDeFutbol.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnioFundacion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadSocios")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Titulos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Equipo");
                });
#pragma warning restore 612, 618
        }
    }
}
