// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcEquiposDeFutbol.Data;

#nullable disable

namespace EquiposDeFutbol.Migrations
{
    [DbContext(typeof(MvcEquiposDeFutbolContext))]
    partial class MvcEquiposDeFutbolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("EquiposDeFutbol.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnioFundacion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadSocios")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LigaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Titulos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LigaId");

                    b.ToTable("Equipo", (string)null);
                });

            modelBuilder.Entity("EquiposDeFutbol.Models.Liga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Liga", (string)null);
                });

            modelBuilder.Entity("EquiposDeFutbol.Models.Equipo", b =>
                {
                    b.HasOne("EquiposDeFutbol.Models.Liga", "Liga")
                        .WithMany("Equipos")
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liga");
                });

            modelBuilder.Entity("EquiposDeFutbol.Models.Liga", b =>
                {
                    b.Navigation("Equipos");
                });
#pragma warning restore 612, 618
        }
    }
}
